### ISSUE TITLE
How can use this module with unstyled PT

### ISSUE THREAD

**Issue by rogrile** [sfxcode/formkit-primevue#28]
I am using Primevue Unstyled with Tailwind, and I have my own components creating using the PT config. However, I see that using tailwind you can use existing tailwind classes, but when you use Unstyled PT, the classes do not exist, so you cannot style using classes, and I was thinking of how I can use my vue components as inputs for the form.

**Comment by sfxcode** [comment]
Hi,
i am still waiting for the official release of the new way of using the unstyled mode (in 2 weeks). For the moment there is sometimes the need of the !important notion to use tailwind classes in pt because the base styleclass from p-input is used for example. I have made a small demo with the last release.

https://formkit-primevue.netlify.app/demo/passThrough

Maybe you can share a short demo if that does not work for you.

Hope that helps a little bit,

Tom

**Comment by rogrile** [comment]
This is great! Also, what about the password weakness meter? Can't seem to put that in there no matter how much I try

**Comment by sfxcode** [comment]
Hi, please use the feedback attribute:

```  {
    "$formkit": "primePassword",
    "name": "password",
    "label": "Password",
    "help": "Enter your new password",
    "feedback": true
  },
```

**Comment by rogrile** [comment]
Hey, is there a way I could find all these options anywhere? I didn't see this feedback option while going through the docs.

**Comment by rogrile** [comment]
Either way, you're doing a great job, thanks a lot!

**Comment by sfxcode** [comment]
Hi, i try to add more documentation soon, will close this issue meanwhile
