### ISSUE TITLE
Support for PrimeVue component prefix

### ISSUE THREAD

**Issue by StevenGFX** [sfxcode/formkit-primevue#43]
Great project! I see that Primevue component prefixes are not currently supported [here](https://github.com/sfxcode/nuxt3-primevue-starter/issues/38). Will this change in the future? I think it would be helpful to note this in the documentation. I went down a rabbit hole 🤦

**Comment by sfxcode** [comment]
Hi, sorry for causing trouble.

 At the moment i have no good idea how to implement, but i will think about it  ... 
If i add a prefix, all others will stick to my prefix because the PrimeVue component names are part of the wrapper classes.

Meanwhile i will add a note in the README file.

Are you using different component libraries that force you to prefix PrimeVue ?

Have a nice coding time and thank you for your input,

Tom
