### ISSUE TITLE
PrimeVue components not detected on Nuxt+Tailwind+PrimeVue 4 (unstyled)+FormKit

### ISSUE THREAD

**Issue by lmc3s3f0r** [sfxcode/formkit-primevue#52]
I'm struggling to get formkit-primevue to work on my Nuxt project. PrimeVue is on unstyled mode, as I'm using my custom preset/theme and Tailwind css integration (they recommend using unstyled mode in this case).

I've made a new project from scratch to illustrate the problem:
https://github.com/lmc3s3f0r/bug_sfxcode_formkit_primevue

Clone it, run npm i and then npm run dev, and this is what you should see:
![image](https://github.com/user-attachments/assets/c2c98ba6-5f5d-41ac-a0b5-c06ec09e50d2)

Form left to right:
1 - The example provided in [sfxcode/formkit-primevue page](https://sfxcode.github.io/formkit-primevue/guide/getting-started.html). When you reload the page you can see some components, but after hydration their styles disappear. I think this is happening because sfxcode's plugin is injecting classes like "p-inputtext p-component p-filled" in the components, but that shouldn't be done in unstyled mode. Check the InputText both in this section and in the third section (plain PrimeVue components) and you'll see no p-* classes are added in unstyled mode.

2 - A plain FormKit form as seen in their documentation, with plain html inputs. No styles applied, and I don't worry about it because I want to use PrimeVue, but adding that in case it leads to something related to the problem.

3 - PrimeVue components working perfectly. Styles are properly applied.

I get this hydration warning in the console:
![image](https://github.com/user-attachments/assets/fc2d4767-9c36-43e9-89a2-f24ddf082164)

Any help is greatly appreciated.

**Comment by sfxcode** [comment]
Hi,

first problem is that the first component does not reflect your unstyled mode. atm you can change this by set unstyled to true in the json. After that you shoud be able to see your styling. Maybe i find a better way in the next releases.

Second Problem your button in formkit is styled as p-component. You have to use for the button class some tailwind styling and enable the Button in the nuxt config.

Actual i prefer for myself the styled mode with tailwind / unocss styling on top of it. imho there are some glitches with the unstyled mode but it is getting better with every version.

Hope it helps you for a first shot ...

Greetings,

Tom

**Comment by molul** [comment]
Hi Tom. Thanks for the quick reply. Oh, I'm the same guy from the OP (this is my personal account, the other is from work) :)

I do have unstyled=true in primevue options in nuxt.config.ts, not sure if you mean I should add it to another object in the nuxt config file. Is that possible? 

To clarify, the styles you see in the right panel are just tailwind classes coming from my theme (which is mostly primevue's main theme). They display fine because primevue is not adding p-* classes.

I'll try to explain better: 

-With my current configuration (unstyled=true), plain Primevue components work perfectly. Primevue is not adding any p-* class, and style is created from a theme with tailwind classes.

-With same configuration, in the same project, using formit-primevue, p-* classes are injected in Primevue components by your plugin, even though I have unstyled set to true in primevue options. 

The ideal solution would be the your plugin didn't inject any p-* class in Primevue components when in unstyled mode. Is there any way to configure your plugin like that?

**Comment by molul** [comment]
Tried setting unstyled to false just in case, but it's still not working. Rolled back to unstyled= true.

**Comment by molul** [comment]
More tests: tried setting unstyled to false in the project I mentioned in the OP and that does work, so I'll try to migrate that to my apps. Crossing fingers.

Thanks for the help again :)

**Comment by sfxcode** [comment]
made a new version that tries to use the config option of unstyled in the PrimeVue components.

https://github.com/sfxcode/formkit-primevue/releases/tag/v2.4.10

maybe that fix your problem in your provided showcase ...

**Comment by sfxcode** [comment]
<img width="572" alt="Bildschirmfoto 2024-09-18 um 21 28 51" src="https://github.com/user-attachments/assets/eeee0178-a317-453a-865f-3a3311231831">

After using the latest version 2.4.10 your styles are back with your showcase, submit button should be styled as tailwind to show up ...

**Comment by molul** [comment]
> made a new version that tries to use the config option of unstyled in the PrimeVue components.
> 
> https://github.com/sfxcode/formkit-primevue/releases/tag/v2.4.10
> 
> maybe that fix your problem in your provided showcase ...

It does! Awww yeah, thank you very much! :D

**Comment by sfxcode** [comment]
Hi, glad it helps.

I will close this issue for now. 
If there will be other problems let me know and good luck with your tailwind integration ...

Greetings, Tom
