### ISSUE TITLE
Type of primevue input prop not correctly inferred

### ISSUE THREAD

**Issue by Brads3290** [sfxcode/formkit-primevue#66]
In the following code, the type of `options` is expected to be `undefined`, so TS raises an error when I try to assign a `string[]`.

```
<div>
    <FormKit type="primeSelect" name="region" label="Region" :options="['option 1', 'option 2']" />
</div>
```

![CleanShot 2024-11-18 at 11 33 51@2x](https://github.com/user-attachments/assets/16fc2d19-7406-4b0b-af3e-cfe03395f2e8)

This is a Nuxt project, set up in the following way:
- `@formkit/nuxt` module
- `@sfxcode/formkit-primevue-nuxt` module with `formkitAutoConfig: false`
- A `formkit.config.ts` file (used by `@formkit/nuxt`) which manually loads the PV components from `@sfxcode/formkit-primevue`

**Comment by sfxcode** [comment]
Please try with latest version. 

Note: formkitAutoConfig is replaced by installFormKit and the module now (since 1.2.x) depends on formkit-nuxt like your provided configuration. Without configuration @formkit/nuxt is installed by the module, so no need to install by yourself (dependencies to @formkit/nuxt is provided).

Hope it helps,

Greetings, Tom

**Comment by Brads3290** [comment]
@sfxcode Seems to work - thanks :)
